{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangem",
    "module": "tangem-sdk-android",
    "version": "5.18.409-local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tangem-sdk-android-5.18.409-local.aar",
          "url": "tangem-sdk-android-5.18.409-local.aar",
          "size": 616535,
          "sha512": "d71c024bc3572667c1e13ed1607a259db686d6eaa6af5bf051183fc6f4f2edbdcd9c58d7538a0e4c7304eb5a661db9e0773c83ff86eae20faf273a7f65a0dee1",
          "sha256": "f27628ec6d0eebfc189026184becb3208a8a09f2280ba9cfb9f9a9453dd3964c",
          "sha1": "105344333357a92288964df13516761bbf6bb869",
          "md5": "abccba3a8e5962261478afe816d72ba7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tangem",
          "module": "tangem-sdk-core",
          "version": {
            "requires": "5.18.409-local"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.skyfishjy.ripplebackground",
          "module": "library",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "armadillo",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "tangem-sdk-android-5.18.409-local.aar",
          "url": "tangem-sdk-android-5.18.409-local.aar",
          "size": 616535,
          "sha512": "d71c024bc3572667c1e13ed1607a259db686d6eaa6af5bf051183fc6f4f2edbdcd9c58d7538a0e4c7304eb5a661db9e0773c83ff86eae20faf273a7f65a0dee1",
          "sha256": "f27628ec6d0eebfc189026184becb3208a8a09f2280ba9cfb9f9a9453dd3964c",
          "sha1": "105344333357a92288964df13516761bbf6bb869",
          "md5": "abccba3a8e5962261478afe816d72ba7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tangem-sdk-android-5.18.409-local-sources.jar",
          "url": "tangem-sdk-android-5.18.409-local-sources.jar",
          "size": 136353,
          "sha512": "43cdd4bf0381a9d9a3fdc9ac6a2db8301cd8fc29cf3b4c9297708c595f2e50cb7eedb42de2427fe97303b4cc0d675a7f845c378a2954e324453869df9456da47",
          "sha256": "4d8b4063e793bcaef0e127c5f7c1a9a3015d399874ef4908499b049023efb23e",
          "sha1": "1f6d9547f017a3f8e75bb15b311b40ec8cc2cfb0",
          "md5": "2342bb1fa48e6ceedc4d91181911cb60"
        }
      ]
    }
  ]
}
